server:
  port: 9102
  tomcat:
    basedir: ./tomcat
spring:
  application:
    name: springboot-websocket
  profiles:
    active: local
  devtools:
    restart:
      #设置开启热部署
      enabled: true
      #重启目录
      additional-exclude: src/main/java
      exclude: resources/**
  thymeleaf:
    encoding: utf-8
    #页面不加载缓存，修改即时生效
    cache: false
    mode: HTML5

